server:
  port: 3010

spring:
  profiles:
    active: dev
  datasource:
    username: ${jc.datasource.username}
    password: ${jc.datasource.password}
    driver-class-name: ${jc.datasource.driver-class-name}
    url: jdbc:mysql://${jc.datasource.host}:${jc.datasource.port}/${jc.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true/characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    type: ${jc.datasource.type}
    druid:
      initial-size: 20  # 初始化连接池大小
      min-idle: 20      # 最小空闲连接数
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};  # 连接属性，包括解密配置和公钥
      max-active: 100   # 最大活跃连接数
      max-wait: 60000   # 获取连接的最大等待时间（毫秒）
      stat-view-servlet:
        enabled: true    # 是否启用Druid监控页面
        url-pattern: ${jc.datasource.druid.url-pattern}  # Druid监控页面的URL路径
        login-username: ${jc.datasource.druid.login-username}  # 登录Druid监控页面的用户名
        login-password: ${jc.datasource.druid.login-password}  # 登录Druid监控页面的密码
        filter:
          stat:
            enabled: true  # 启用统计过滤器
            slow-sql-millis: 2000  # 设置慢查询阈值为2000毫秒
            log-slow-sql: true  # 记录慢查询日志
          wall: # 定义防火墙过滤器
            enabled: true  # 启用防火墙过滤器
          config: # 定义配置过滤器
            enabled: true  # 启用配置过滤器
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKDYQUFao8cjnYSA0MU8W4LoD+3xuiG+pao6KyvSIEAeMfKmx4CxiDLjG1M9VMZ7JeHWyWgaVqiE2gUuVx2gjt0CAwEAAQ==


logging:
  config: classpath:log4j2-spring.xml


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package：用于给Java类型设置一个别名，以便在MyBatis的映射文件中更方便地引用。
  #这个属性指定了一个包名，MyBatis将会为该包下的所有类创建别名，别名是类名（不包括包名），默认是小写。这可以避免在XML映射文件中使用完全限定类名。
  #例如，如果你有一个com.sky.entity.User类，并且type-aliases-package设置为com.sky.entity，
  #则可以在XML映射文件中直接使用User作为别名来代替完全限定名com.sky.entity.User。
  type-aliases-package: com.sky.entity
  #  configuration：这是一个占位符，表示MyBatis的详细配置信息将在这里提供。在这个属性下面，你可以添加各种MyBatis的配置元素
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

# mp提供的sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









